# Generated by Django 3.2.14 on 2023-09-20 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillsToPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=50, verbose_name='descrição')),
                ('barcode', models.CharField(blank=True, max_length=59, null=True, verbose_name='Código de Barras')),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'contas a pagar',
                'verbose_name_plural': 'contas a pagar',
                'ordering': ['date', 'description'],
            },
        ),
        migrations.CreateModel(
            name='BillsToReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=50, verbose_name='descrição')),
                ('received', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'contas a receber',
                'verbose_name_plural': 'contas a receber',
                'ordering': ['date', 'description'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='FinancialTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.financialcategory')),
            ],
            options={
                'verbose_name': 'termo de categoria',
                'verbose_name_plural': 'termos de categoria',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[['E', 'Entrada'], ['S', 'Saída']], max_length=1)),
                ('date', models.DateField(default=datetime.datetime(2023, 9, 20, 9, 56, 15, 611167, tzinfo=utc))),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.financialcategory')),
            ],
            options={
                'verbose_name': 'fluxo de caixa',
                'verbose_name_plural': 'fluxos de caixa',
                'ordering': ['category', '-date', 'description'],
            },
        ),
    ]
