# Generated by Django 3.2.14 on 2022-08-05 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='ContasAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=50, verbose_name='descrição')),
                ('codigo_barras', models.CharField(blank=True, max_length=59, null=True, verbose_name='Código de Barras')),
                ('pago', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'contas a pagar',
                'verbose_name_plural': 'contas a pagar',
                'ordering': ['data', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='ContasAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=50, verbose_name='descrição')),
                ('recebido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'contas a receber',
                'verbose_name_plural': 'contas a receber',
                'ordering': ['data', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='TermoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.categoria')),
            ],
            options={
                'verbose_name': 'termo de categoria',
                'verbose_name_plural': 'termos de categoria',
            },
        ),
        migrations.CreateModel(
            name='FluxoDeCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[['E', 'Entrada'], ['S', 'Saída']], max_length=1)),
                ('data', models.DateField(default=datetime.datetime(2022, 8, 5, 12, 35, 29, 721676, tzinfo=utc))),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=50, verbose_name='descrição')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.categoria')),
            ],
            options={
                'verbose_name': 'fluxo de caixa',
                'verbose_name_plural': 'fluxos de caixa',
                'ordering': ['categoria', '-data', 'descricao'],
            },
        ),
    ]
