# Generated by Django 3.2.14 on 2022-09-12 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxodecaixa',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 9, 12, 13, 47, 38, 55863, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fluxodecaixa',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='descrição'),
        ),
    ]
