# Generated by Django 3.2.14 on 2022-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('chave', models.CharField(max_length=43)),
                ('senha', models.CharField(max_length=43)),
                ('verificada', models.BooleanField(default=False)),
            ],
        ),
    ]
